import {
  Home,
  UtensilsCrossed,
  Car,
  Film,
  Pill,
  GraduationCap,
  ShoppingBag,
  FileText,
  Package,
  DollarSign,
  Briefcase,
  TrendingUp,
  Gift,
  Wallet,
  Repeat,
  Users,
  HandCoins,
} from 'lucide-react'

export const TRANSACTION_CATEGORIES = [
  'perumahan',
  'makanan',
  'transport',
  'hiburan',
  'kesehatan',
  'pendidikan',
  'belanja',
  'tagihan',
  'gaji',
  'investasi',
  'freelance',
  'hadiah',
  'lainnya',
  'tidak_diketahui',
  'topup_ewallet',
  'transfer_internal',
  'transfer_keluarga',
  'transfer_sosial',
]

export const CATEGORY_LABELS = {
  perumahan: 'Perumahan',
  makanan: 'Makanan',
  transport: 'Transport',
  hiburan: 'Hiburan',
  kesehatan: 'Kesehatan',
  pendidikan: 'Pendidikan',
  belanja: 'Belanja',
  tagihan: 'Tagihan',
  gaji: 'Gaji',
  investasi: 'Investasi',
  freelance: 'Freelance',
  hadiah: 'Hadiah',
  lainnya: 'Lainnya',
  tidak_diketahui: 'Tidak Diketahui',
  topup_ewallet: 'Top Up E-Wallet',
  transfer_internal: 'Transfer Internal',
  transfer_keluarga: 'Transfer Keluarga',
  transfer_sosial: 'Transfer Sosial',
}

export const CATEGORY_ICON_MAP = {
  perumahan: Home,
  makanan: UtensilsCrossed,
  transport: Car,
  hiburan: Film,
  kesehatan: Pill,
  pendidikan: GraduationCap,
  belanja: ShoppingBag,
  tagihan: FileText,
  gaji: DollarSign,
  investasi: TrendingUp,
  freelance: Briefcase,
  hadiah: Gift,
  lainnya: Package,
  tidak_diketahui: Package,
  topup_ewallet: Wallet,
  transfer_internal: Repeat,
  transfer_keluarga: Users,
  transfer_sosial: HandCoins,
}

export const CATEGORY_COLORS = {
  perumahan: '#8b5cf6',
  makanan: '#f97316',
  transport: '#3b82f6',
  hiburan: '#ec4899',
  kesehatan: '#ef4444',
  pendidikan: '#6366f1',
  belanja: '#f59e0b',
  tagihan: '#64748b',
  gaji: '#22c55e',
  investasi: '#06b6d4',
  freelance: '#8b5cf6',
  hadiah: '#e879f9',
  lainnya: '#94a3b8',
  tidak_diketahui: '#94a3b8',
  topup_ewallet: '#14b8a6',
  transfer_internal: '#6366f1',
  transfer_keluarga: '#ec4899',
  transfer_sosial: '#f97316',
}

export const TRANSACTION_FILTERS = [
  { key: 'all', label: 'Semua' },
  { key: 'income', label: 'Masuk' },
  { key: 'expense', label: 'Keluar' },
]

export const LEDGER_FILTERS = [
  { key: 'all', label: 'Semua' },
  { key: 'lainnya', label: 'Lainnya' },
  { key: 'tidak_diketahui', label: 'Tidak Diketahui' },
]

export const ALL_CATEGORIES = [
  'makanan',
  'transport',
  'hiburan',
  'belanja',
  'tagihan',
  'kesehatan',
  'pendidikan',
  'lainnya',
  'transfer_keluarga',
  'transfer_sosial',
  'tidak_diketahui',
  'topup_ewallet',
  'transfer_internal',
]
